- name: variables
  hosts: localhost
  connection: local
  vars:
    course: "devops"
    trainer: "siva"
    duration: "14hrs"
  tasks:
   - name: demo on variables
     vars:
      course: "devsecops with aiops"
     debug:
       msg: "hi i am learning {{ course }},trainer is {{ trainer }}, duration is {{ duration }}"