---
- name: Prompt for Username and Password
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: login_user
      prompt: "Enter your username"
      private: false  # Makes the text visible while typing

    - name: login_password
      prompt: "Enter your password"
      private: true   # Hides input on screen for security

  tasks:
    - name: Display the username
      ansible.builtin.debug:
        msg: "The user entered is {{ login_user }},the password entered is {{ login_password }}"
