- name: variables
  hosts: frontend
  #connection: local
  tasks:
   - name: demo on variables
     debug:
       msg: "hi i am learning {{ course }},trainer is {{ trainer }}, duration is {{ duration }}, cammon key {{ common_key }}"