- name: name
  hosts: localhost
  connection: local
  vars:
   name: "sundar"
  vars_files:
   - course.yaml
  vars_prompt:
   - name: name
     prompt: please entered
     private: false  
 tasks:
 - name: print
   vars:
    name: "ramesh"
   debug:
    msg: "{{ name }}"
