- name: install package
  hosts: local
  become: yes
  tasks:
  - name: install package
    package:
     name: "{{ item }}"
     state: present

    loop:
    - nginx
    - git
    - mongodb-mongosh
    - mysql   